#  静态资源默认位置在ResourceProperties中
#  ResourceProperties
#
#    private static final String[] CLASSPATH_RESOURCE_LOCATIONS = {
#    "classpath:/META-INF/resources/", "classpath:/resources/",
#    "classpath:/static/", "classpath:/public/" };

server:
  port: 9080
  servlet.context-path: /web/rest
spring:
  application:
    name: spring-boot-web
  mvc:
    static-path-pattern: /static/**   # 过滤规则
  resources:
    static-locations: /static/ #静态资源位置
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration # 去除error的自动配置类
eureka:
  instance:
    prefer-ip-address: true
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl.defaultZone: http://localhost:8761/eureka/