
# 详细介绍见 C:/Users/Administrator/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.1.1.RELEASE/spring-boot-autoconfigure-2.1.1.RELEASE.jar!/META-INF/spring-configuration-metadata.json:2
# 官方文档中的配置 http://tomcat.apache.org/tomcat-8.0-doc/config/http.html#Common_Attributes

server:
  servlet:
    context-path: /config
    session:
      timeout: 30m # 默认30分钟，如果不写单位，默认单位是秒，并且将秒转换成分钟，向下取整，如599秒，转换成9分钟
  tomcat:
    max-threads: 500  # 默认200
    uri-encoding: UTF-8 # 默认UTF-8
    basedir: /home/config/tmp
    accept-count:
  error:
    path: /error  # 当项目出错跳转去页面

