server:
  port: 8000
eureka:
  instance:
    prefer-ip-address: false
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl.defaultZone: http://localhost:8761/eureka/   #纯eureka的url
    #serviceUrl.defaultZone: http://admin:admin@localhost:8761/eureka/   jhipster 的url
spring:
  application:
    name: spring-boot-admin